### ISSUE TITLE
clientOnly option not working and unable to remove mods

### ISSUE THREAD

**Issue by Sir-Will** [JadedPacks/JadedLibs#1]
The Agrarian Skies modpack downloads the defined clientOnly mods for the server.

There is also no way to disable mods without editing the jadedlibs.json

**Comment by ghost** [comment]
Are we on about 1.6.4 here, or 1.7.10?

**Comment by Sir-Will** [comment]
1.6.4

**Comment by ghost** [comment]
Make sure you're running the latest version of JadedLibs, or temporaryily disable it :) This feature was only added in (1.0.3?)

**Comment by ghost** [comment]
We added support for ".disabled" files in the 1.0.6 update; https://github.com/JadedPacks/JadedLibs/commit/a57229e1b3e500c0acbd011a055993f117a36b1d
